### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by xolife3** [chenchenwuai/tieba-delete#6]
C:\Users\Administrator\Desktop\tieba-delete-master>node index
'node' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\Administrator\Desktop\tieba-delete-master>

**Comment by chenchenwuai** [comment]
> C:\Users\Administrator\Desktop\tieba-delete-master>node index 'node' 不是内部或外部命令，也不是可运行的程序 或批处理文件。
> 
> C:\Users\Administrator\Desktop\tieba-delete-master>

你这是node没运行起来，和这个项目无关
